version: '3.8'

services:
  trading-bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - TZ=America/New_York  # Set timezone for market hours
      - LOG_LEVEL=INFO 